---
application:
  name: "matomo"
  project: "project"
  organization: "QoveryCommunity"
  storage:
  - name: "mainimage"
    size: "10"
    type: "fast_ssd"
    mount_point: "/mnt/mainimage"
databases:
- type: "MYSQL"
  name: "matomo-mysql"
  version: "8"
routers:
- name: "main-matomo"
  routes:
  - application_name: "matomo"
    paths:
    - "/*"
